# Generated by Django 3.1.6 on 2021-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
