# Generated by Django 3.1.6 on 2021-02-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='favourite',
        ),
    ]
