# Generated by Django 3.1.6 on 2021-02-26 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0005_auto_20210223_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_ingredient', to=settings.AUTH_USER_MODEL),
        ),
    ]
