# Generated by Django 3.1.6 on 2021-05-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_auto_20210514_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
    ]
