# Generated by Django 3.1.6 on 2021-03-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='list_ingredient',
        ),
    ]
