# Generated by Django 3.1.6 on 2021-05-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='DiseaseCategory',
        ),
    ]
