# Generated by Django 3.1.6 on 2021-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_favourites'),
        ('disease', '0002_remove_disease_list_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='disease',
            name='list_ingredient',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='disease_ingredients', to='ingredients.Ingredient'),
        ),
    ]
