# Generated by Django 3.1.6 on 2021-03-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_auto_20210322_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='disease',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_disease', to='diseases.disease'),
        ),
    ]
