# Generated by Django 3.1.6 on 2021-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_favourites'),
        ('diseases', '0003_auto_20210322_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='self_ingredients',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='self_ingredients',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='blacklist_ingredients', to='ingredients.Ingredient'),
        ),
    ]
