# Generated by Django 3.1.6 on 2021-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
