# Generated by Django 3.1.6 on 2021-04-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_favourites'),
        ('recipes', '0002_auto_20210330_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='list_ingredient',
            field=models.ManyToManyField(blank=True, related_name='recipe_list_ingredient', to='ingredients.Ingredient'),
        ),
    ]
