# Generated by Django 3.1.6 on 2021-04-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210407_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cart',
        ),
    ]
