# Generated by Django 3.1.6 on 2021-04-27 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='direction|text')),
                ('image', models.ImageField(upload_to='directions/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='recipes.direction'),
        ),
    ]
