# Generated by Django 3.1.6 on 2021-04-28 06:53

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210427_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AddField(
            model_name='direction',
            name='order',
            field=positions.fields.PositionField(blank=True, default=-1, null=True),
        ),
    ]
