# Generated by Django 3.1.6 on 2021-03-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_favourites'),
        ('recipes', '0008_recipe_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='list_ingredient',
            field=models.ManyToManyField(blank=True, to='ingredients.Ingredient'),
        ),
    ]
