# Generated by Django 3.1.6 on 2021-04-28 07:09

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210428_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='order',
            field=positions.fields.PositionField(blank=True, default=1, null=True),
        ),
    ]
