# Generated by Django 3.1.6 on 2021-04-28 10:58

from django.db import migrations, models
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210428_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='MeasurementUnit')),
            ],
        ),
        migrations.AlterField(
            model_name='direction',
            name='order',
            field=positions.fields.PositionField(blank=True, default=-1, null=True),
        ),
    ]
