# Generated by Django 3.1.6 on 2021-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210428_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementunits',
            options={'verbose_name': 'MeasurementUnit', 'verbose_name_plural': 'MeasurementUnits'},
        ),
        migrations.AlterField(
            model_name='measurementunits',
            name='name',
            field=models.TextField(verbose_name='MeasurementUnit|text'),
        ),
    ]
