# Generated by Django 3.1.6 on 2021-04-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210428_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementunits',
            options={'verbose_name': 'Measurement Unit', 'verbose_name_plural': 'Measurement Units'},
        ),
    ]
