# Generated by Django 3.1.6 on 2021-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210428_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_amount', models.TextField(verbose_name='Qty amount')),
            ],
        ),
    ]
