# Generated by Django 3.1.6 on 2021-04-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_measurementqty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementqty',
            options={'verbose_name': 'Measurement qty', 'verbose_name_plural': 'Measurement qty'},
        ),
    ]
