# Generated by Django 3.1.6 on 2021-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipe_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.TextField(blank=True, help_text='Enter time in minutes or hours', max_length=100, verbose_name='preparation time'),
        ),
    ]
