# Generated by Django 3.1.6 on 2021-05-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_favourites'),
        ('recipes', '0019_auto_20210428_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementqty',
            name='ingredient',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='measurementqty',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='measurementqty',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementunits'),
        ),
    ]
