# Generated by Django 3.1.6 on 2021-05-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20210505_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementqty',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementunits'),
        ),
    ]
