# Generated by Django 3.1.6 on 2021-05-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20210505_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='list_ingredient',
        ),
    ]
