# Generated by Django 3.1.6 on 2021-05-05 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_favourites'),
        ('recipes', '0022_remove_recipe_list_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementqty',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='measurementqty',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='measurementqty',
            name='unit',
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementqty')),
                ('ingredient', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementunits')),
            ],
        ),
    ]
