# Generated by Django 3.1.6 on 2021-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20210505_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Recipe Ingredients', 'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.IntegerField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MeasurementQty',
        ),
    ]
