# Generated by Django 3.1.6 on 2021-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20210505_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.FloatField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
