# Generated by Django 3.1.6 on 2021-05-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0041_auto_20210511_0229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='RecipeCategory',
        ),
    ]
