# Generated by Django 3.1.6 on 2021-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_auto_20210516_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(blank=True, help_text='Enter time in minutes or hours', max_length=10, verbose_name='preparation time'),
        ),
    ]
