# Generated by Django 3.1.6 on 2021-06-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0045_remove_recipe_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='the_timedelta',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
