# Generated by Django 3.1.6 on 2021-03-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0006_ingredient_favourites'),
        ('disease', '0003_auto_20210316_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='list_ingredient',
            field=models.ManyToManyField(blank=True, default=None, related_name='disease_ingredients', to='ingredients.Ingredient'),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ManyToManyField(blank=True, default=None, related_name='blacklist_disease', to='disease.Disease')),
                ('self_ingredients', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_ingredients', to='ingredients.ingredient')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
