# Generated by Django 3.1.6 on 2021-03-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_favourites'),
        ('disease', '0004_auto_20210316_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='self_ingredients',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='self_ingredients',
            field=models.ManyToManyField(blank=True, default=None, related_name='blacklist_ingredients', to='ingredients.Ingredient'),
        ),
    ]
